name: Pull Request Review

on:
  pull_request_review:
    types:
      - submitted

jobs:
  handle_pull_request_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Handle pull request review
        run: python handle_pull_request_review.py
