name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your build and test steps here

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Add your deployment steps here
