on:
  push:
    branches:
      - main
  issues:
    types: [labeled]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  autopr:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check if label was added by a collaborator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        if [ "${{ github.event.sender.type }}" != "Bot" ]; then
            echo "Label not added by a collaborator. Skipping action."
            exit 78
          fi
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 1
      - name: AutoPR
        uses: irgolic/AutoPR@latest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: main