name: Issue Handling

on:
  issues:
    types:
      - opened
      - edited

jobs:
  handle_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Build and deploy
        run: |
          npm install
          npm run build
          npm run deploy

      - name: Store output and analyze for self-improvement
        run: |
          python store_output.py
          python analyze.py
