name: PR Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pr_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Analyze pull request
        run: python analyze_pull_request.py

      - name: Review pull request
        run: python review_pull_request.py

      - name: Test pull request review
        run: python test_pull_request_review.py
